### ISSUE TITLE
saving an html as exe imo has room for improvements

### ISSUE THREAD

**Issue by pmario** [ihm4u/twexe#1]
hi,

I think your intentions are ok, but imo the implementation has some room for improvements. 

I think this program has a viral behaviour. It saves itself at several positions to the hard disk. For me this is _not_ ok. Also all backups are executables. ... 

I may be overreacting, but I think you create a huge attack vector for the whole community here. 

I'd kindly request to disable the download links for some time, so we can discuss improvements first. 

![twexe-viral-behaviour](https://cloud.githubusercontent.com/assets/374655/11868263/d387ae86-a4b6-11e5-899f-adc75f86d97e.png)

@Jermolene What do you think?

**Comment by ihm4u** [comment]
The only way to keep to the single executable paradigm and be able to update the data within it is to save itself to another location. Security is a lot more complicated than what you think. ANY executable can do malicious things if it wanted to, the difference here is that the source code is freely available and anyone can look at it and see if it does malicious things under the covers.

If you show me a line of code that does a malicious thing under the covers I would be more than happy to erase anything you want.

By the way, you are simply responding to the windows dialog box that says that it is an untrusted executable, but Tiddlydesktop includes also an non-signed untrusted executable, NW.exe. But the dialog  never shows up because Jermolene distributed it as a zip file. Like I said before, true security is much much more than a simple dialog box not showing up.

**Comment by tobibeer** [comment]
@pmario,

I'd agree with @ihm4u that there are no grounds to retract twexe, at all.

Why would "because it is an executable that creates executables" be a cause for concern in itself?

You have to point out actual exploits for your concern(s) to be substantiated. The mere existence of potentially vulnerable pieces of software on a machine does not make for a compromised machine.

You actually need malicious code to exploit those vulnerabilities... that you have yet to show.

But then again, the idea alone that someone would build that based on an assumption of (a user) having twexe for that bit of code to exploit sounds quite... ficticious.

Also, if someone wanted to redistribute malicious code disguised as a friendly twexe christmas present, they can do so with pretty much all the software in the world. Doesn't take twexe for that.

You are free to not feel comfortable with using an executable of this kind. But, to suggest it involved a security thread, I'd urge you to do some actual investigations first, rather than argue and create an atmosphere of concern ...based on a hunch alone.

**Comment by pmario** [comment]
I did respond at: https://groups.google.com/d/msg/tiddlywiki/Zq2bnToz0qs/JclrHI0pBwAJ

**Comment by tobibeer** [comment]
@pmario, I do agree with one thing: exchanging (even self-modifying) executables doesn't sound like something a safety expert would recommend or an IT admin would possibly allow at their network.

Exchanging wiki html files sounds a lot less of a security risk. If I decide to use some twexe-server-cli to simplify editing it, then that is my choice.

**Comment by ihm4u** [comment]
I'll close this issue since there has not been any specific threat pointed out in the source code.
